# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: ✅ Checks

on:
  workflow_dispatch:
  pull_request:
  release:
    types:
      - published
      - unpublished
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library.yml@4.0.0
    with:
      library: libhal-rmd
      coverage: true
    secrets: inherit

  deploy:
    uses: libhal/ci/.github/workflows/deploy.yml@4.0.0
    secrets: inherit

  build_lpc4074:
    uses: libhal/ci/.github/workflows/demo_builder.yml@4.0.0
    with:
      profile: lpc4074
      processor_profile: https://github.com/libhal/libhal-armcortex.git
      platform_profile: https://github.com/libhal/libhal-lpc40.git
    secrets: inherit

  build_lpc4078:
    uses: libhal/ci/.github/workflows/demo_builder.yml@4.0.0
    with:
      profile: lpc4078
      processor_profile: https://github.com/libhal/libhal-armcortex.git
      platform_profile: https://github.com/libhal/libhal-lpc40.git
    secrets: inherit
